#include <strings.h>
#include "common.h"
#include "../lib/pao_utf8.h"

typedef struct {
  u8 buffer[32];
  usize buff_size;
  bool  valid;

  pao_Rune expected;
} TestCase;

// This array was generated by an LLM using Markus Kuhn utf8 stress test as basis.
// Available at: https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt
TestCase testcases[] = {
  // ----------------------------------------------------------------
  // VALID: ASCII boundaries
  // ----------------------------------------------------------------
  // 2.1.1 - U+0000, null character
  {{0x00}, 1, true, 0x0000},
  // 2.2.1 - U+007F, last ASCII
  {{0x7f}, 1, true, 0x007F},
  // plain ASCII letter
  {{'a'}, 1, true, 'a'},

  // ----------------------------------------------------------------
  // VALID: 2-byte boundaries
  // ----------------------------------------------------------------
  // 2.1.2 - U+0080, first 2-byte
  {{0xc2, 0x80}, 2, true, 0x0080},
  // 2.2.2 - U+07FF, last 2-byte
  {{0xdf, 0xbf}, 2, true, 0x07FF},

  // ----------------------------------------------------------------
  // VALID: 3-byte boundaries
  // ----------------------------------------------------------------
  // 2.1.3 - U+0800, first 3-byte
  {{0xe0, 0xa0, 0x80}, 3, true, 0x0800},
  // 2.2.3 - U+FFFF (not a character, but valid encoding)
  {{0xef, 0xbf, 0xbf}, 3, true, 0xFFFF},
  // 2.3.1 - U+D7FF, last codepoint before surrogate range
  {{0xed, 0x9f, 0xbf}, 3, true, 0xD7FF},
  // 2.3.2 - U+E000, first codepoint after surrogate range
  {{0xee, 0x80, 0x80}, 3, true, 0xE000},
  // 2.3.3 - U+FFFD, replacement character
  {{0xef, 0xbf, 0xbd}, 3, true, 0xFFFD},
  // ⌘ U+2318
  {{0xe2, 0x8c, 0x98}, 3, true, 0x2318},
  // € U+20AC
  {{0xe2, 0x82, 0xac}, 3, true, 0x20AC},

  // ----------------------------------------------------------------
  // VALID: 4-byte boundaries
  // ----------------------------------------------------------------
  // 2.1.4 - U+10000, first 4-byte
  {{0xf0, 0x90, 0x80, 0x80}, 4, true, 0x10000},
  // 2.3.4 - U+10FFFF, last valid Unicode codepoint
  {{0xf4, 0x8f, 0xbf, 0xbf}, 4, true, 0x10FFFF},
  // 😀 U+1F600
  {{0xf0, 0x9f, 0x98, 0x80}, 4, true, 0x1F600},

  // ----------------------------------------------------------------
  // INVALID: bare continuation bytes (section 3.1)
  // ----------------------------------------------------------------
  // 3.1.1 - 0x80, first continuation byte
  {{0x80}, 1, false, PAO_utf8_invalid},
  // 3.1.2 - 0xbf, last continuation byte
  {{0xbf}, 1, false, PAO_utf8_invalid},

  // ----------------------------------------------------------------
  // INVALID: overlong sequences (section 4)
  // ----------------------------------------------------------------
  // 4.1.1 - overlong '/' (U+002F) as 2 bytes
  {{0xc0, 0xaf}, 2, false, PAO_utf8_invalid},
  // 4.1.2 - overlong '/' as 3 bytes
  {{0xe0, 0x80, 0xaf}, 3, false, PAO_utf8_invalid},
  // 4.1.3 - overlong '/' as 4 bytes
  {{0xf0, 0x80, 0x80, 0xaf}, 4, false, PAO_utf8_invalid},
  // 4.2.1 - U+007F overlong as 2 bytes
  {{0xc1, 0xbf}, 2, false, PAO_utf8_invalid},
  // 4.2.2 - U+07FF overlong as 3 bytes
  {{0xe0, 0x9f, 0xbf}, 3, false, PAO_utf8_invalid},
  // 4.2.3 - U+FFFF overlong as 4 bytes
  {{0xf0, 0x8f, 0xbf, 0xbf}, 4, false, PAO_utf8_invalid},
  // 4.3.1 - overlong NUL as 2 bytes
  {{0xc0, 0x80}, 2, false, PAO_utf8_invalid},
  // 4.3.2 - overlong NUL as 3 bytes
  {{0xe0, 0x80, 0x80}, 3, false, PAO_utf8_invalid},
  // 4.3.3 - overlong NUL as 4 bytes
  {{0xf0, 0x80, 0x80, 0x80}, 4, false, PAO_utf8_invalid},

  // ----------------------------------------------------------------
  // INVALID: surrogate pairs (section 5.1)
  // ----------------------------------------------------------------
  // 5.1.1 - U+D800, first high surrogate
  {{0xed, 0xa0, 0x80}, 3, false, PAO_utf8_invalid},
  // 5.1.4 - U+DBFF, last high surrogate
  {{0xed, 0xaf, 0xbf}, 3, false, PAO_utf8_invalid},
  // 5.1.5 - U+DC00, first low surrogate
  {{0xed, 0xb0, 0x80}, 3, false, PAO_utf8_invalid},
  // 5.1.7 - U+DFFF, last low surrogate
  {{0xed, 0xbf, 0xbf}, 3, false, PAO_utf8_invalid},

  // ----------------------------------------------------------------
  // INVALID: beyond U+10FFFF (section 2.3.5)
  // ----------------------------------------------------------------
  // 2.3.5 - U+110000, first out-of-range 4-byte
  {{0xf4, 0x90, 0x80, 0x80}, 4, false, PAO_utf8_invalid},
  // 2.2.4 - U+1FFFFF, max encodable by 4-byte format but beyond Unicode
  {{0xf7, 0xbf, 0xbf, 0xbf}, 4, false, PAO_utf8_invalid},

  // ----------------------------------------------------------------
  // INVALID: ill-formed lead bytes
  // ----------------------------------------------------------------
  // 0xfe and 0xff are never valid in UTF-8
  {{0xfe}, 1, false, PAO_utf8_invalid},
  {{0xff}, 1, false, PAO_utf8_invalid},
};

bool test_utf8_decode(void) {
  int len = (int)(sizeof(testcases) / sizeof(testcases[0]));
  int i = 0;
  while (i < len) {
    TestCase t = testcases[i];
    pao_UTF8DecodeReturn ret = pao_utf8_decode(t.buffer, t.buff_size);
    bool validDecode = (ret.status == PAO_status_ok);
    if (validDecode != t.valid) {
      return false;
    }
    if (validDecode && ret.r != t.expected) {
      return false;
    }
    i++;
  }
  return true;
}

/* BEGIN: DRIVER CODE */
Tester tests[] = {
  {"test_utf8_decode", test_utf8_decode},
  // {"test_utf8_encode", test_utf8_encode},
};

int main(void) {
  run_tests("utf8", tests, (int)(sizeof(tests) / sizeof(tests[0])));
}
/* END: DRIVER CODE */
